version: 0.2

phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo 'Test stage'
      - test -f build/index.html || (echo "index.html not found" && exit 1)