version: 0.2

phases:
  install:
    commands:
      - npm ci
  pre_build:
    commands:
      - ls -la
      - node --version
      - npm --version
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - ls -la